config/routes.rb
 PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get "/register", to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy' 

  resources :posts, except: :destroy do
    member do
      post :vote
    end

    resources :comments, only: [:create, :vote] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:show, :create, :new]
  resources :users, only: [:create, :show, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base 
  include Slug
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  slugable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :post 
  
  validates :body, presence: true
  
end

app/models/post.rb
class Post < ActiveRecord::Base 
  include Voteable
  include Slug

	belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true
  validates :user, presence: true

  slugable_column :title

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base 
  belongs_to :post
  belongs_to :category
end

app/models/postcategory.rb
class Postcategory < ActiveRecord::Base 
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base 
  include Slug
	has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, uniqueness: true, presence: true, length: {minimum: 3}
  validates :password, presence: true, length: {minimum: 3}, on: :create

  slugable_column :username

  def admin?
    self.role == "admin"  
  end

  

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

	#validates_uniqueness_of :user, scope: :voteable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_category

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to to access this"
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless current_user.admin?
    
  end

  def access_denied
    flash[:error] = "You can't access this area"
    redirect_to root_path
  end

  private
  def set_category
    @category_sort = Category.all.sort_by{|a| a.name}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:show]
  before_action :require_admin, only: [:new, :create]

  def show
    @category = Category.find_by slug: params[:id]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Your category has been created"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user 
  before_action :set_post

  def create
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Your post has been created"
      redirect_to post_path(@post)
    else
      render "posts/show"
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])

    respond_to do |format|
      
      format.html do
        if @vote.save
          flash[:notice] = "Your vote has been counted"
        else
          flash[:error] = "You have already voted on this"
        end
      redirect_to :back
      end

      format.js
    end
  end

  private

  def set_post
    @post = Post.find_by slug: params[:post_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:create, :edit, :update]

  def index
    @posts = Post.all.sort_by{|e| e.total_votes}.reverse
  end

  def show
    @comment = Comment.new 
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Your post has been created"
      redirect_to root_path
    else
      render :new
    end

  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your Post has been updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      
      format.html do
        if @vote.save
          flash[:notice] = "Your vote has been counted"
        else
          flash[:error] = "You have already voted on this"
        end
        redirect_to :back
      end

      format.js
      
    end

    
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :url, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def require_creator
    access_denied unless @post.user == current_user or current_user.admin?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [:destroy]
  
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back #{user.username}. You are now logged in."
      redirect_to root_path
    else
      flash[:error] = "There is something wrong with your username or password"
      redirect_to login_path
    end
  end

  def destroy
    flash[:notice] = "Good bye #{current_user.username}. You are now logged out"
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create, :show]
  before_action :set_user, except: [:new, :create]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Your user account has been created"
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account details have been updated"
      render :edit
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end

  def require_same_user
    if @user != current_user
      flash[:error] = "You can only modify your own profile"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    if str.starts_with?("http://")
      str
    else
      "http://#{str}"
    end    
  end

  def display_datetime(dt)
    if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
    end
    dt.strftime("%d/%m/%y at %l:%M%p %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> </span> 

app/views/categories/index.html.erb
<%= render "shared/content_title", title: "Categories" %>

<% @category.each do |cat| %>
  <span class="badge"><%= cat.name %></span>
<% end %>

app/views/categories/new.html.erb
<%= render "shared/content_title", title: "Create new category" %>
<%= render "/shared/error", obj: @category %>

<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, placeholder: "Insert category name here" %> 
      </div>
      <br>
      <%= f.submit "Create category", class: "btn btn-success" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts',posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render "shared/content_title", title: header %>

<% @category.posts.each do |cat| %>
  <%= render "/posts/post", post: cat %>
<% end %>
 

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class="row">

<div class="span0 well text-center">
  <% if logged_in? %>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: "post", remote: true do %>
      <i class="icon-arrow-up"> </i>
    <% end %>
  <br>
  <% end %>
  <span id="comment_<%= comment.id %>_vote"><%= comment.total_votes %> votes</span>
  <% if logged_in? %>
  <br>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: "post", remote: true do %>
      <i class="icon-arrow-down"> </i>
    <% end %>
  <% end %>
</div>

  <div class="well span8">
    <em>
      "<%= comment.body %>"
      <% if show_post %>
         on <%= link_to comment.post.description, post_path(comment.user) %>
      <% end %>
    </em>
    <br>
    <span class="quiet">
      Comment by <%= link_to comment.user.username, user_path(comment.user) %> 
    </span>
    <small>
      on the <%= display_datetime(comment.created_at) %>
    </small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
	$("#comment_<%= @comment.id %>_vote").html("<%= @comment.total_votes %> votes")
<% else %>
	alert("You can only vote once")
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    
  </li>
</ul>


<ul class="nav_item">
  <!-- Category Dropdown Button -->
  <div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
     Categories
     <span class="caret"></span>
    </a>

    <ul class="dropdown-menu">
  <!-- Category options -->
      <% @category_sort.each do |cat| %>
        <li>
          <%= link_to cat.name, category_path(cat.slug) %>
        </li>
      <% end %>
  <!-- Create New Category (show if logged in) -->
      <% if logged_in? and current_user.admin? %>
        <li class="divider"></li>
        <li>
          <%= link_to(new_category_path) do %>
            <i class="icon-plus"></i>
            New Category
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <!-- Show if Logged in -->
  <% if logged_in? %>
  <!-- Create New Post -->
  <div class="btn-group">
    <%= link_to 'New Post', new_post_path, class: "btn btn-success btn-small" %>
  </div>
  <div class="btn-group">
  <!-- Dropdown User Button -->
    <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
      <%= current_user.username %>
      <span class="caret"></span>
    </a>

  <!-- Dropdown User Options -->
    <ul class="dropdown-menu">
      <li>
        <%= link_to '<i class="icon-pencil"></i> Edit Profile'.html_safe, edit_user_path(current_user) %>
      </li>
      <li>
        <%= link_to '<i class="icon-user"></i> View Profile'.html_safe, user_path(current_user) %>
      </li>
      <li>
        <%= link_to '<i class="icon-circle-arrow-left"></i> Logout'.html_safe, logout_path %>
      </li>
    </ul>
  </div>

  <% else %>

  <!-- Show if not logged in -->
  <%= link_to 'Login', login_path, class: "btn btn-success btn-small" %>
  <%= link_to 'Register', register_path, class: "btn btn-success btn-small" %>

  <% end %>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "/shared/error", obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title, "Title of the Post:" %>
      <%= f.text_field :title, placeholder: "Please insert title" %>
    </div>
    <div class="control-group">
      <%= f.label :url, "Web site address" %>
      <%= f.text_field :url, placeholder: "example: www.google.com" %>
    </div>
    <div class="control-group">
      <%= f.label :description, "Describe this site:" %>
      <%= f.text_area :description, rows: 5, placeholder: "Why should people look at this site?" %>
    </div>
    <div class="control-group">
      <%= f.collection_check_boxes :category_ids, Category.all.sort_by{|a| a.name}, :id, :name do |cb| %>
        <%= cb.label class: "checkbox inline" %>
        <%= cb.check_box class: "checkbox" %>
      <% end %>
    </div>
    <br>
    <%= f.submit "Create Post", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">

  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: "post", remote: true do %>
        <i class="icon-arrow-up"> </i>
      <br>
      <% end %>
    <% end %>
    <span id="post_<%= post.slug %>_votes"><%= post.total_votes %> votes</span>
    <% if logged_in? %>
      <br>
      <%= link_to vote_post_path(post, vote: false), method: "post", remote: true do %>
        <i class="icon-arrow-down"> </i>
      <% end %>
    <% end %>
    </div>

  <div class="span8 well">
    <%= render post.categories %>
    <h4> 
      <%= link_to post.title, fix_url(post.url) %> 
    </h4>
    <p>
      <%= post.description %>
    </p>
    <p>
      <span class="quiet">
        Created by <%= link_to post.user.username, user_path(post.user) %> 
      </span>
      <small>
        at <%= display_datetime(post.created_at) %>
      </small>
    </p>
    <small>
      <span>
        <%= link_to "#{post.comments.size} comments", post_path(post) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "shared/content_title", title: "Edit a post" %>

<%= render "form" %>

app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All Posts" %>
<% @posts.each do |post| %>
  <%= render "post", post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/content_title", title: "Create a new post" %>


<%= render "form" %>

app/views/posts/show.html.erb
<% if current_user == @post.user or current_user.admin?%>
  <p class="pull-right">
  [<%= link_to "Edit this post", edit_post_path(@post)%>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>
<%= render 'shared/content_title', title: @post.title %>

<p><%= @post.description %></p>
<hr>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render "/shared/error", obj: @comment %>
    <div class="control-group">
      <%= f.label :body, "Leave a comment" %>
      <%= f.text_area :body, rows: 3, class: "span4" %>
    </div>
    <%= f.submit class: "btn btn-success btn-small" %>
  <% end %>
<% end %>

<h5>Comments:</h5>
<% if @post.comments.any? %>
  <% @post.comments.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
  <% end %>
<% else %>
  There are no comments yet...  
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes")
<% else %>
	alert("You can only vote once")
<% end %>

app/views/shared/_content_title.html.erb
<p class="lead"> <%= title %>
  <hr>
</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-error">

    <% if obj.errors.count == 1 %>
      <H5>There is an error:</H5>
    <% else %>
      <H5>There were some errors:</H5>
    <% end %>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "/shared/error", obj: @user %>

<div class="well">
  <%= form_for @user do |f| %>
    <div class="control-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="control-group">
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all, default: Time.zone.name %>
    </div>
    <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: "btn btn-success btn-small" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render "/shared/content_title", title: "Edit Profile" %>

<%= render "form" %>

app/views/users/new.html.erb
<%= render "shared/content_title", title: "Register a new account" %>

<%= render "form" %>

app/views/users/show.html.erb
<%= render "shared/content_title", title: "Profile: #{@user.username}" %>

<div class="well">
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Time zone:</dt>
    <dd><%= @user.time_zone %> Time</dd>
    <dt>Two factor auth:</dt>
    <dd>TO ADD</dd>
    <dt>Phone:</dt>
    <dd>TO ADD</dd>
  </dl>
</div>

<ul class="nav nav-tabs">
  <li class="<%= "active" if params[:tab].nil? %>">
    <%= link_to "Posts (#{@user.posts.count})", user_path(@user) %>
  </li>
  <li class="<%= "active" if params[:tab] == "comments" %>">
    <%= link_to "Comments (#{@user.comments.count})", user_path(@user, tab: "comments")%>
  </li>
</ul>

<%# -- Posts or Comments -- %>

<% if params[:tab].nil? %>

  <% @user.posts.each do |post| %>
    <%= render "/posts/post", post: post %>
  <% end %>

<% elsif params[:tab] == "comments" %>

  <% @user.comments.each do |comment| %>
    <%= render "/comments/comment", comment: comment, show_post: true %>
  <% end %>

<% end %>